### PR TITLE
Upgrade Trex

### PR DESCRIPTION
**Pull request by jadsonlourenco**

### CODE REVIEW

**Comment by PTRFRLL** [comment]
Thanks for the PR. Would you mind updating Trex in the cuda10 Dockerfile as well?

**Comment by jadsonlourenco** [comment]
ok.

**Comment by PTRFRLL** [comment]
I meant in this PR 😂 No worries, I'll merge both.

**Comment by jadsonlourenco** [comment]
Sorry, I tried, but I'm doing this on Github directly, I will learn for next time. hahaha
Thanks.

**Pull request merged**
